# Generated by Django 5.0.7 on 2024-07-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("potatoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="potato",
            name="is_acquired",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
