# Generated by Django 5.0.7 on 2024-07-28 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("potatoes", "0001_initial"),
        (
            "users",
            "__first__",
        ),  # users 앱의 첫 번째 마이그레이션 파일을 dependency로 추가
    ]

    operations = [
        migrations.AddField(
            model_name="potato",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
