# Generated by Django 5.0.7 on 2024-07-29 14:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("potatoes", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="potato",
            old_name="potato_type_id",
            new_name="potato_type",
        ),
    ]
