# Generated by Django 5.0.7 on 2024-07-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Baekjoon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일자"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
                (
                    "bj_name",
                    models.CharField(max_length=255, verbose_name="백준 아이디"),
                ),
                ("score", models.BigIntegerField(verbose_name="백준 점수")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
