# Generated by Django 5.0.7 on 2024-07-24 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("baekjoons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="baekjoon",
            name="username",
            field=models.CharField(
                default=2, max_length=255, verbose_name="백준 아이디"
            ),
            preserve_default=False,
        ),
    ]
