# Generated by Django 5.0.7 on 2024-07-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baekjoons", "0002_baekjoon_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baekjoon",
            old_name="username",
            new_name="bj_id",
        ),
    ]
