# Generated by Django 5.0.7 on 2024-07-24 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baekjoons", "0003_rename_username_baekjoon_bj_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="baekjoon",
            old_name="bj_id",
            new_name="bj_name",
        ),
    ]
