# Generated by Django 5.0.7 on 2024-07-25 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("baekjoons", "0004_rename_bj_id_baekjoon_bj_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="baekjoon",
            name="bj_name",
        ),
    ]
