# Generated by Django 5.0.7 on 2024-07-23 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendances", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendance",
            old_name="user_id",
            new_name="user",
        ),
    ]
