# Generated by Django 5.0.7 on 2024-07-29 16:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("potato_types", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="potatotype",
            name="potato_image",
        ),
    ]
