# Generated by Django 5.0.7 on 2024-08-01 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("potato_types", "0002_add_initial_data"),
        ("potato_types", "0003_remove_potatotype_potato_image"),
    ]

    operations = []
