# Generated by Django 5.0.7 on 2024-08-01 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("potato_types", "0004_merge_20240731_1547"),
        ("potato_types", "0004_merge_20240801_1049"),
    ]

    operations = []
