# Generated by Django 5.0.7 on 2024-07-18 06:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stacks", "0001_initial"),
        ("user_stacks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstack",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="생성일자",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userstack",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일자"),
        ),
        migrations.AlterField(
            model_name="userstack",
            name="stack_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="stacks.stack",
                verbose_name="스택아이디",
            ),
        ),
    ]
