# Generated by Django 5.0.7 on 2024-07-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GithubFolder",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일자"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "github_id",
                    models.CharField(max_length=50, verbose_name="깃허브 아이디"),
                ),
                ("commit_num", models.BigIntegerField(verbose_name="커밋숫자")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
