# Generated by Django 5.0.7 on 2024-07-16 01:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Potato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일자"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일자"),
                ),
                ("potato_type_id", models.SmallIntegerField(verbose_name="감자타입")),
                (
                    "potato_nickname",
                    models.CharField(max_length=255, verbose_name="감자닉네임"),
                ),
                ("potato_level", models.IntegerField(verbose_name="감자레벨")),
                ("potato_exp", models.IntegerField(verbose_name="감자경험치")),
                ("potato_coin", models.IntegerField(verbose_name="감자코인")),
                (
                    "is_selected",
                    models.BooleanField(default=False, verbose_name="현재선택상태"),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="유저아이디",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
