# Generated by Django 5.0.7 on 2024-07-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github_access_token",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
