# Generated by Django 5.0.7 on 2024-07-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_github_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="total_coins",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
