# Generated by Django 5.0.7 on 2024-07-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_total_coins"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default=1, max_length=254, verbose_name="email address"
            ),
        ),
    ]
