# Generated by Django 5.0.7 on 2024-07-18 06:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_description_remove_user_login_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="exp",
        ),
        migrations.RemoveField(
            model_name="user",
            name="level",
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="생성일자",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="potato_exp",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="potato_level",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="수정일자"),
        ),
    ]
