# Generated by Django 5.0.7 on 2024-07-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
    ]
