# Generated by Django 5.0.7 on 2024-07-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_rename_nickname_user_username_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="email",
        ),
    ]
