# Generated by Django 5.0.7 on 2024-08-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="date",
            field=models.DateField(),
        ),
    ]
